### ISSUE TITLE
Tons of problems

### ISSUE THREAD

**Issue by hdfsyu** [popdynamite5511/2craft#2]
# Problems (yes its so big)
1. Glass doesn't generate
2. Program crashes when map loads and no output, tried almost every python version
3. Gravel is coming as transparent blocks
***Please fix this immediately***

**Comment by popdynamite5511** [comment]
thank you for reporting, i will start coding a version 1.1.2 right now. However, glass not generating is intended, but there is supposed to be a crafting recipe for it, which I will add.

**Comment by popdynamite5511** [comment]
Ok so the game still crashes on some windows machines, but everything else is fixed.
I am going to close the issue and make a new one with only the crashing bit.
