### ISSUE TITLE
Game crashes on some Windows machines

### ISSUE THREAD

**Issue by popdynamite5511** [popdynamite5511/2craft#3]
As said by hdfsyu: Program crashes when map loads and no output, tried almost every python version
His original report had some other bugs in it that have been fixed, but only this bug has not. I decided to close that issue because everything was fixed except for this, and it would make no sense to keep it up.

**Comment by hdfsyu** [comment]
Yeah but why? Is it some sort of like not found error or something?

**Comment by popdynamite5511** [comment]
yep it seems like it because i can't find a single thing that i think would crash the game. it aint bad optimization, because i have made the game significantly more optimized, and if it can run on my 2009 macbook fine it should work fine on your rtx 3090 with 1tb ram just fine lol

**Comment by hdfsyu** [comment]
it doesnt work XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD even with the new version bruhhhhh

**Comment by popdynamite5511** [comment]
i think what happens is that on high end machines with lots of ram, the game trys to use as much as possible and because of that python goes crazy because it isn't supposed to load the game that fast. idk if i can even fix that lol

**Comment by hdfsyu** [comment]
I TRIED ON MY LOW-END LAPTOP TOO!!!!!!!!!!!!!!!!!!!!!!!

**Comment by popdynamite5511** [comment]
bruh well it seems to work on some peoples pcs. tyuhgjn got it to work easily once i got him to download python

**Comment by popdynamite5511** [comment]
Ok try on the new release

**Comment by w68YuhIojn** [comment]
my pc is low end thats why

**Comment by popdynamite5511** [comment]
going to close this because everyone can open the game except for you now, so at this point it must be something on your end
